name: Tauon Apple Silicon DMG

on:
  workflow_dispatch:  # Enables manual triggering from the GitHub Actions UI
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensures that submodules are cloned recursively

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0  # Specify the Python version you need

      - name: Install system dependencies
        run: |
          # Install all necessary dependencies
          brew install pygobject3 gtk+3 python pyinstaller libao sdl2 sdl2_image flac mpg123 opusfile libopenmpt libsamplerate libvorbis librsvg wavpack libgme ffmpeg@5 pango cairo harfbuzz gobject-introspection ninja autoconf automake pkg-config

      - name: Install Python dependencies from requirements-mac.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-mac.txt

      - name: Compile Phazor
        run: |
          # Run the specified compilation script for Phazor
          bash compile-phazor.sh

      - name: Build macOS app with PyInstaller
        run: |
          pyinstaller mac.spec --clean --noconfirm

      - name: Create DMG
        run: |
          mkdir -p dist/dmg
          APP_NAME="TauonMusicBox"
          APP_PATH="dist/${APP_NAME}.app"
          DMG_PATH="dist/dmg/Tauon-macOS-AppleSilicon.dmg"
          
          # Create a .dmg package with the updated name
          hdiutil create -volname "$APP_NAME" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_PATH"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Adjust the tag name for versioning
          release_name: Tauon Apple Silicon DMG
          draft: false
          prerelease: false

      - name: Upload DMG to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/dmg/Tauon-macOS-AppleSilicon.dmg
          asset_name: Tauon-macOS-AppleSilicon.dmg
          asset_content_type: application/octet-stream
