name: Build macOS App & DMG

on:
  workflow_dispatch:  # This enables manual triggering from the GitHub Actions UI
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensures that submodules are cloned recursively

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0  # specify the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          brew install gtk+3 pango cairo harfbuzz ffmpeg

      - name: Build macOS app with PyInstaller
        run: |
          pyinstaller mac.spec --clean --noconfirm

      - name: Create DMG
        run: |
          mkdir -p dist/dmg
          APP_NAME="TauonMusicBox"
          APP_PATH="dist/${APP_NAME}.app"
          DMG_PATH="dist/dmg/Tauon-macOS-AppleSilicon.dmg"
          
          # Create a .dmg package with the updated name
          hdiutil create -volname "$APP_NAME" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_PATH"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: TauonMusicBox-dmg
          path: dist/dmg/Tauon-macOS-AppleSilicon.dmg
